version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: loan-postgres
    environment:
      POSTGRES_DB: loan_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loan-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: loan-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - loan-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: loan-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - loan-network

volumes:
  postgres_data:

networks:
  loan-network:
    driver: bridge
